name: fortune_1000_companies
description: A list of fortune_1000_companies.
version: 0.1.0
author: Brady Becker <bradybeck@gmail.com>
homepage: http://github.com/bradybeck/fortune_1000_companies

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
    coverage: ^0.7.2
    dart_dev: ^1.1.1
    dart_style: ^0.2.4
    dartdoc: ">=0.8.0 <0.10.0"
    test: ^0.12.4
