name: fortune_1000_companies
version: 0.1.0
description: A list of fortune_1000_companies.
author: Brady Becker <bradybeck@gmail.com>
homepage: http://github.com/bradybeck/fortune_1000_companies

environment:
  sdk: '>=1.24.3 <3.0.0'

dev_dependencies:
  build_runner: ">=0.6.0 <2.0.0"
  build_test: ">=0.9.0 <2.0.0"
  build_web_compilers: ">=0.2.0 <2.0.0"
  dart_dev: ^2.0.0
  dart_style: ^1.0.9
  test: ">=0.12.30 <2.0.0"
